export const dialvalues = [
  { label: "Turkey", id: "+90", value: "TR", flag: "🇹🇷" },
  { label: "Egypt", id: "+20", value: "EG", flag: "🇪🇬", digitsLength: 10 },
  {
    label: "Saudi Arabia",
    id: "+966",
    value: "SA",
    flag: "🇸🇦",
    digitsLength: 9,
  },
  {
    label: "United Arab Emirates",
    id: "+971",
    value: "AE",
    preferred: !0,
    flag: "🇦🇪",
    digitsLength: 9,
  },
  { label: "Afghanistan", id: "+93", value: "AF", flag: "🇦🇫" },
  { label: "Albania", id: "+355", value: "AL", flag: "🇦🇱" },
  { label: "Algeria", id: "+213", value: "DZ", flag: "🇩🇿" },
  { label: "AmericanSamoa", id: "+1684", value: "AS", flag: "🇦🇸" },
  { label: "Andorra", id: "+376", value: "AD", flag: "🇦🇩" },
  { label: "Angola", id: "+244", value: "AO", flag: "🇦🇴" },
  { label: "Anguilla", id: "+1264", value: "AI", flag: "🇦🇮" },
  { label: "Antarctica", id: "+672", value: "AQ", flag: "🇦🇶" },
  { label: "Antigua and Barbuda", id: "+1268", value: "AG", flag: "🇦🇬" },
  { label: "Argentina", id: "+54", value: "AR", flag: "🇦🇷" },
  { label: "Armenia", id: "+374", value: "AM", flag: "🇦🇲" },
  { label: "Aruba", id: "+297", value: "AW", flag: "🇦🇼" },
  {
    label: "Australia",
    id: "+61",
    value: "AU",
    preferred: !0,
    flag: "🇦🇺",
  },
  { label: "Austria", id: "+43", value: "AT", flag: "🇦🇹" },
  { label: "Azerbaijan", id: "+994", value: "AZ", flag: "🇦🇿" },
  { label: "Bahamas", id: "+1242", value: "BS", flag: "🇧🇸" },
  {
    label: "Bahrain",
    id: "+973",
    value: "BH",
    flag: "🇧🇭",
    digitsLength: 8,
  },
  { label: "Bangladesh", id: "+880", value: "BD", flag: "🇧🇩" },
  { label: "Barbados", id: "+1246", value: "BB", flag: "🇧🇧" },
  { label: "Belarus", id: "+375", value: "BY", flag: "🇧🇾" },
  { label: "Belgium", id: "+32", value: "BE", flag: "🇧🇪" },
  { label: "Belize", id: "+501", value: "BZ", flag: "🇧🇿" },
  { label: "Benin", id: "+229", value: "BJ", flag: "🇧🇯" },
  { label: "Bermuda", id: "+1441", value: "BM", flag: "🇧🇲" },
  { label: "Bhutan", id: "+975", value: "BT", flag: "🇧🇹" },
  {
    label: "Bolivia, Plurinational State of",
    id: "+591",
    value: "BO",
    flag: "🇧🇴",
  },
  { label: "Bosnia and Herzegovina", id: "+387", value: "BA", flag: "🇧🇦" },
  { label: "Botswana", id: "+267", value: "BW", flag: "🇧🇼" },
  { label: "Brazil", id: "+55", value: "BR", flag: "🇧🇷" },
  {
    label: "British Indian Ocean Territory",
    id: "+246",
    value: "IO",
    flag: "🇮🇴",
  },
  { label: "Brunei Darussalam", id: "+673", value: "BN", flag: "🇧🇳" },
  { label: "Bulgaria", id: "+359", value: "BG", flag: "🇧🇬" },
  { label: "Burkina Faso", id: "+226", value: "BF", flag: "🇧🇫" },
  { label: "Burundi", id: "+257", value: "BI", flag: "🇧🇮" },
  { label: "Cambodia", id: "+855", value: "KH", flag: "🇰🇭" },
  { label: "Cameroon", id: "+237", value: "CM", flag: "🇨🇲" },
  { label: "Canada", id: "+1", value: "CA", flag: "🇨🇦" },
  { label: "Cape Verde", id: "+238", value: "CV", flag: "🇨🇻" },
  { label: "Cayman Islands", id: "+345", value: "KY", flag: "🇰🇾" },
  {
    label: "Central African Republic",
    id: "+236",
    value: "CF",
    flag: "🇨🇫",
  },
  { label: "Chad", id: "+235", value: "TD", flag: "🇹🇩" },
  { label: "Chile", id: "+56", value: "CL", flag: "🇨🇱" },
  { label: "China", id: "+86", value: "CN", flag: "🇨🇳" },
  { label: "Christmas Island", id: "+61", value: "CX", flag: "🇨🇽" },
  { label: "Cocos (Keeling) Islands", id: "+61", value: "CC", flag: "🇨🇨" },
  { label: "Colombia", id: "+57", value: "CO", flag: "🇨🇴" },
  { label: "Comoros", id: "+269", value: "KM", flag: "🇰🇲" },
  { label: "Congo", id: "+242", value: "CG", flag: "🇨🇬" },
  {
    label: "Congo, The Democratic Republic of the",
    id: "+243",
    value: "CD",
    flag: "🇨🇩",
  },
  { label: "Cook Islands", id: "+682", value: "CK", flag: "🇨🇰" },
  { label: "Costa Rica", id: "+506", value: "CR", flag: "🇨🇷" },
  { label: "Cote d'Ivoire", id: "+225", value: "CI", flag: "🇨🇮" },
  { label: "Croatia", id: "+385", value: "HR", flag: "🇭🇷" },
  { label: "Cuba", id: "+53", value: "CU", flag: "🇨🇺" },
  { label: "Cyprus", id: "+357", value: "CY", flag: "🇨🇾" },
  { label: "Czech Republic", id: "+420", value: "CZ", flag: "🇨🇿" },
  { label: "Curaçao", id: "+599", value: "CW", flag: "🇨🇼" },
  { label: "Canary Islands", id: "+34", value: "IC", flag: "🇮🇨" },
  { label: "Denmark", id: "+45", value: "DK", flag: "🇩🇰" },
  { label: "Djibouti", id: "+253", value: "DJ", flag: "🇩🇯" },
  { label: "Dominica", id: "+1767", value: "DM", flag: "🇩🇲" },
  {
    label: "Dominican Republic",
    id: "+1849",
    value: "DO",
    flag: "🇩🇴",
    country_value: "+1",
    area_values: ["849", "829", "809"],
  },
  {
    label: "Dominican Republic",
    id: "+1829",
    value: "DO",
    flag: "🇩🇴",
    secondary: !0,
  },
  {
    label: "Dominican Republic",
    id: "+1809",
    value: "DO",
    flag: "🇩🇴",
    secondary: !0,
  },
  { label: "Ecuador", id: "+593", value: "EC", flag: "🇪🇨" },

  { label: "El Salvador", id: "+503", value: "SV", flag: "🇸🇻" },
  { label: "Equatorial Guinea", id: "+240", value: "GQ", flag: "🇬🇶" },
  { label: "Eritrea", id: "+291", value: "ER", flag: "🇪🇷" },
  { label: "Estonia", id: "+372", value: "EE", flag: "🇪🇪" },
  { label: "Ethiopia", id: "+251", value: "ET", flag: "🇪🇹" },
  {
    label: "Falkland Islands (Malvinas)",
    id: "+500",
    value: "FK",
    flag: "🇫🇰",
  },
  { label: "Faroe Islands", id: "+298", value: "FO", flag: "🇫🇴" },
  { label: "Fiji", id: "+679", value: "FJ", flag: "🇫🇯" },
  { label: "Finland", id: "+358", value: "FI", flag: "🇫🇮" },
  { label: "France", id: "+33", value: "FR", flag: "🇫🇷" },
  { label: "French Guiana", id: "+594", value: "GF", flag: "🇬🇫" },
  { label: "French Polynesia", id: "+689", value: "PF", flag: "🇵🇫" },
  {
    label: "French Southern Territories",
    id: "+262",
    value: "TF",
    flag: "🇹🇫",
  },
  { label: "Gabon", id: "+241", value: "GA", flag: "🇬🇦" },
  { label: "Gambia", id: "+220", value: "GM", flag: "🇬🇲" },
  { label: "Georgia", id: "+995", value: "GE", flag: "🇬🇪" },
  { label: "Germany", id: "+49", value: "DE", flag: "🇩🇪" },
  { label: "Ghana", id: "+233", value: "GH", flag: "🇬🇭" },
  { label: "Gibraltar", id: "+350", value: "GI", flag: "🇬🇮" },
  { label: "Greece", id: "+30", value: "GR", flag: "🇬🇷" },
  { label: "Greenland", id: "+299", value: "GL", flag: "🇬🇱" },
  { label: "Grenada", id: "+1473", value: "GD", flag: "🇬🇩" },
  { label: "Guadeloupe", id: "+590", value: "GP", flag: "🇬🇵" },
  { label: "Guam", id: "+1671", value: "GU", flag: "🇬🇺" },
  { label: "Guatemala", id: "+502", value: "GT", flag: "🇬🇹" },
  { label: "Guernsey", id: "+44", value: "GG", flag: "🇬🇬" },
  { label: "Guinea", id: "+224", value: "GN", flag: "🇬🇳" },
  { label: "Guinea-Bissau", id: "+245", value: "GW", flag: "🇬🇼" },
  { label: "Guyana", id: "+592", value: "GY", flag: "🇬🇾" },
  { label: "Haiti", id: "+509", value: "HT", flag: "🇭🇹" },
  {
    label: "Heard & McDonald Islands",
    id: "+672",
    value: "HM",
    flag: "🇭🇲",
  },
  {
    label: "Holy See (Vatican City State)",
    id: "+379",
    value: "VA",
    flag: "🇻🇦",
  },
  { label: "Honduras", id: "+504", value: "HN", flag: "🇭🇳" },
  { label: "Hong Kong", id: "+852", value: "HK", flag: "🇭🇰" },
  { label: "Hungary", id: "+36", value: "HU", flag: "🇭🇺" },
  { label: "Iceland", id: "+354", value: "IS", flag: "🇮🇸" },
  { label: "India", id: "+91", value: "IN", preferred: !0, flag: "🇮🇳" },
  { label: "Indonesia", id: "+62", value: "ID", flag: "🇮🇩" },
  {
    label: "Iran, Islamic Republic of",
    id: "+98",
    value: "IR",
    flag: "🇮🇷",
  },
  { label: "Iraq", id: "+964", value: "IQ", flag: "🇮🇶" },
  { label: "Ireland", id: "+353", value: "IE", flag: "🇮🇪" },
  { label: "Isle of Man", id: "+44", value: "IM", flag: "🇮🇲" },
  { label: "Italy", id: "+39", value: "IT", flag: "🇮🇹" },
  {
    label: "Jamaica",
    id: "+1876",
    value: "JM",
    flag: "🇯🇲",
    country_value: "+1",
    area_values: ["876", "658"],
  },
  {
    label: "Jamaica",
    id: "+1658",
    value: "JM",
    flag: "🇯🇲",
    secondary: !0,
  },
  { label: "Japan", id: "+81", value: "JP", flag: "🇯🇵" },
  { label: "Jersey", id: "+44", value: "JE", flag: "🇯🇪" },
  {
    label: "Jordan",
    id: "+962",
    value: "JO",
    flag: "🇯🇴",
    digitsLength: 9,
  },
  { label: "Kazakhstan", id: "+77", value: "KZ", flag: "🇰🇿" },
  { label: "Kenya", id: "+254", value: "KE", flag: "🇰🇪" },
  { label: "Kiribati", id: "+686", value: "KI", flag: "🇰🇮" },
  {
    label: "Korea, Democratic People's Republic of",
    id: "+850",
    value: "KP",
    flag: "🇰🇵",
  },
  { label: "Korea, Republic of", id: "+82", value: "KR", flag: "🇰🇷" },
  {
    label: "Kuwait",
    id: "+965",
    value: "KW",
    flag: "🇰🇼",
    digitsLength: 8,
  },
  { label: "Kyrgyzstan", id: "+996", value: "KG", flag: "🇰🇬" },
  { label: "Kosovo", id: "+383", value: "XK", flag: "🇽🇰" },
  {
    label: "Lao People's Democratic Republic",
    id: "+856",
    value: "LA",
    flag: "🇱🇦",
  },
  { label: "Latvia", id: "+371", value: "LV", flag: "🇱🇻" },
  { label: "Lebanon", id: "+961", value: "LB", flag: "🇱🇧" },
  { label: "Lesotho", id: "+266", value: "LS", flag: "🇱🇸" },
  { label: "Liberia", id: "+231", value: "LR", flag: "🇱🇷" },
  { label: "Libyan Arab Jamahiriya", id: "+218", value: "LY", flag: "🇱🇾" },
  { label: "Liechtenstein", id: "+423", value: "LI", flag: "🇱🇮" },
  { label: "Lithuania", id: "+370", value: "LT", flag: "🇱🇹" },
  { label: "Luxembourg", id: "+352", value: "LU", flag: "🇱🇺" },
  { label: "Macao", id: "+853", value: "MO", flag: "🇲🇴" },
  {
    label: "Macedonia, The Former Yugoslav Republic of",
    id: "+389",
    value: "MK",
    flag: "🇲🇰",
  },
  { label: "Madagascar", id: "+261", value: "MG", flag: "🇲🇬" },
  { label: "Malawi", id: "+265", value: "MW", flag: "🇲🇼" },
  { label: "Malaysia", id: "+60", value: "MY", flag: "🇲🇾" },
  { label: "Maldives", id: "+960", value: "MV", flag: "🇲🇻" },
  { label: "Mali", id: "+223", value: "ML", flag: "🇲🇱" },
  { label: "Malta", id: "+356", value: "MT", flag: "🇲🇹" },
  { label: "Marshall Islands", id: "+692", value: "MH", flag: "🇲🇭" },
  { label: "Martinique", id: "+596", value: "MQ", flag: "🇲🇶" },
  { label: "Mauritania", id: "+222", value: "MR", flag: "🇲🇷" },
  { label: "Mauritius", id: "+230", value: "MU", flag: "🇲🇺" },
  { label: "Mayotte", id: "+262", value: "YT", flag: "🇾🇹" },
  { label: "Mexico", id: "+52", value: "MX", flag: "🇲🇽" },
  {
    label: "Micronesia, Federated States of",
    id: "+691",
    value: "FM",
    flag: "🇫🇲",
  },
  { label: "Moldova, Republic of", id: "+373", value: "MD", flag: "🇲🇩" },
  { label: "Monaco", id: "+377", value: "MC", flag: "🇲🇨" },
  { label: "Mongolia", id: "+976", value: "MN", flag: "🇲🇳" },
  { label: "Montenegro", id: "+382", value: "ME", flag: "🇲🇪" },
  { label: "Montserrat", id: "+1664", value: "MS", flag: "🇲🇸" },
  { label: "Morocco", id: "+212", value: "MA", flag: "🇲🇦" },
  { label: "Mozambique", id: "+258", value: "MZ", flag: "🇲🇿" },
  { label: "Myanmar", id: "+95", value: "MM", flag: "🇲🇲" },
  { label: "Namibia", id: "+264", value: "NA", flag: "🇳🇦" },
  { label: "Nauru", id: "+674", value: "NR", flag: "🇳🇷" },
  { label: "Nepal", id: "+977", value: "NP", flag: "🇳🇵" },
  { label: "Netherlands", id: "+31", value: "NL", flag: "🇳🇱" },
  { label: "Caribbean Netherlands", id: "+599", value: "BQ", flag: "🇧🇶" },
  { label: "New Caledonia", id: "+687", value: "NC", flag: "🇳🇨" },
  { label: "New Zealand", id: "+64", value: "NZ", flag: "🇳🇿" },
  { label: "Nicaragua", id: "+505", value: "NI", flag: "🇳🇮" },
  { label: "Niger", id: "+227", value: "NE", flag: "🇳🇪" },
  { label: "Nigeria", id: "+234", value: "NG", flag: "🇳🇬" },
  { label: "Niue", id: "+683", value: "NU", flag: "🇳🇺" },
  { label: "Norfolk Island", id: "+672", value: "NF", flag: "🇳🇫" },
  {
    label: "Northern Mariana Islands",
    id: "+1670",
    value: "MP",
    flag: "🇲🇵",
  },
  { label: "Norway", id: "+47", value: "NO", flag: "🇳🇴" },
  { label: "Oman", id: "+968", value: "OM", flag: "🇴🇲", digitsLength: 8 },
  { label: "Pakistan", id: "+92", value: "PK", flag: "🇵🇰" },
  { label: "Palau", id: "+680", value: "PW", flag: "🇵🇼" },
  {
    label: "Palestinian Territory, Occupied",
    id: "+970",
    value: "PS",
    flag: "🇵🇸",
  },
  { label: "Panama", id: "+507", value: "PA", flag: "🇵🇦" },
  { label: "Papua New Guinea", id: "+675", value: "PG", flag: "🇵🇬" },
  { label: "Paraguay", id: "+595", value: "PY", flag: "🇵🇾" },
  { label: "Peru", id: "+51", value: "PE", flag: "🇵🇪" },
  { label: "Philippines", id: "+63", value: "PH", flag: "🇵🇭" },
  { label: "Pitcairn", id: "+872", value: "PN", flag: "🇵🇳" },
  { label: "Poland", id: "+48", value: "PL", flag: "🇵🇱" },
  { label: "Portugal", id: "+351", value: "PT", flag: "🇵🇹" },
  {
    label: "Puerto Rico",
    id: "+1939",
    value: "PR",
    flag: "🇵🇷",
    country_value: "+1",
    area_values: ["939", "787"],
  },
  {
    label: "Puerto Rico",
    id: "+1787",
    value: "PR",
    flag: "🇵🇷",
    secondary: !0,
  },
  { label: "Qatar", id: "+974", value: "QA", flag: "🇶🇦", digitsLength: 8 },
  { label: "Romania", id: "+40", value: "RO", flag: "🇷🇴" },
  { label: "Russia", id: "+7", value: "RU", flag: "🇷🇺" },
  { label: "Rwanda", id: "+250", value: "RW", flag: "🇷🇼" },
  { label: "Réunion", id: "+262", value: "RE", flag: "🇷🇪" },
  { label: "Saint Barthélemy", id: "+590", value: "BL", flag: "🇧🇱" },
  {
    label: "Saint Helena, Ascension and Tristan Da Cunha",
    id: "+290",
    value: "SH",
    flag: "🇸🇭",
  },
  { label: "Saint Kitts and Nevis", id: "+1869", value: "KN", flag: "🇰🇳" },
  { label: "Saint Lucia", id: "+1758", value: "LC", flag: "🇱🇨" },
  { label: "Saint Martin", id: "+590", value: "MF", flag: "🇲🇫" },
  {
    label: "Saint Pierre and Miquelon",
    id: "+508",
    value: "PM",
    flag: "🇵🇲",
  },
  {
    label: "Saint Vincent and the Grenadines",
    id: "+1784",
    value: "VC",
    flag: "🇻🇨",
  },
  { label: "Samoa", id: "+685", value: "WS", flag: "🇼🇸" },
  { label: "San Marino", id: "+378", value: "SM", flag: "🇸🇲" },
  { label: "Sao Tome and Principe", id: "+239", value: "ST", flag: "🇸🇹" },
  { label: "Senegal", id: "+221", value: "SN", flag: "🇸🇳" },
  { label: "Serbia", id: "+381", value: "RS", flag: "🇷🇸" },
  { label: "Seychelles", id: "+248", value: "SC", flag: "🇸🇨" },
  { label: "Sierra Leone", id: "+232", value: "SL", flag: "🇸🇱" },
  { label: "Singapore", id: "+65", value: "SG", flag: "🇸🇬" },
  { label: "Slovakia", id: "+421", value: "SK", flag: "🇸🇰" },
  { label: "Slovenia", id: "+386", value: "SI", flag: "🇸🇮" },
  { label: "Solomon Islands", id: "+677", value: "SB", flag: "🇸🇧" },
  { label: "Somalia", id: "+252", value: "SO", flag: "🇸🇴" },
  { label: "South Africa", id: "+27", value: "ZA", flag: "🇿🇦" },
  {
    label: "South Georgia and the South Sandwich Islands",
    id: "+500",
    value: "GS",
    flag: "🇬🇸",
  },
  { label: "Spain", id: "+34", value: "ES", flag: "🇪🇸" },
  { label: "Sri Lanka", id: "+94", value: "LK", flag: "🇱🇰" },
  { label: "Sudan", id: "+249", value: "SD", flag: "🇸🇩" },
  { label: "South Sudan", id: "+211", value: "SS", flag: "🇸🇸" },
  { label: "Surilabel", id: "+597", value: "SR", flag: "🇸🇷" },
  { label: "Svalbard and Jan Mayen", id: "+47", value: "SJ", flag: "🇸🇯" },
  { label: "Swaziland", id: "+268", value: "SZ", flag: "🇸🇿" },
  { label: "Sweden", id: "+46", value: "SE", flag: "🇸🇪" },
  { label: "Switzerland", id: "+41", value: "CH", flag: "🇨🇭" },
  { label: "Syrian Arab Republic", id: "+963", value: "SY", flag: "🇸🇾" },
  { label: "Sint Maarten", id: "+721", value: "SX", flag: "🇸🇽" },
  {
    label: "Taiwan, Province of China",
    id: "+886",
    value: "TW",
    flag: "🇹🇼",
  },
  { label: "Tajikistan", id: "+992", value: "TJ", flag: "🇹🇯" },
  {
    label: "Tanzania, United Republic of",
    id: "+255",
    value: "TZ",
    flag: "🇹🇿",
  },
  { label: "Thailand", id: "+66", value: "TH", flag: "🇹🇭" },
  { label: "Timor-Leste", id: "+670", value: "TL", flag: "🇹🇱" },
  { label: "Togo", id: "+228", value: "TG", flag: "🇹🇬" },
  { label: "Tokelau", id: "+690", value: "TK", flag: "🇹🇰" },
  { label: "Tonga", id: "+676", value: "TO", flag: "🇹🇴" },
  { label: "Trinidad and Tobago", id: "+1868", value: "TT", flag: "🇹🇹" },
  { label: "Tunisia", id: "+216", value: "TN", flag: "🇹🇳" },
  { label: "Turkmenistan", id: "+993", value: "TM", flag: "🇹🇲" },
  {
    label: "Turks and Caicos Islands",
    id: "+1649",
    value: "TC",
    flag: "🇹🇨",
  },
  { label: "Tuvalu", id: "+688", value: "TV", flag: "🇹🇻" },
  { label: "Uganda", id: "+256", value: "UG", flag: "🇺🇬" },
  { label: "Ukraine", id: "+380", value: "UA", flag: "🇺🇦" },

  {
    label: "United Kingdom",
    id: "+44",
    value: "GB",
    preferred: !0,
    flag: "🇬🇧",
  },
  {
    label: "United States",
    id: "+1",
    value: "US",
    preferred: !0,
    flag: "🇺🇸",
  },
  { label: "Uruguay", id: "+598", value: "UY", flag: "🇺🇾" },
  { label: "Uzbekistan", id: "+998", value: "UZ", flag: "🇺🇿" },
  { label: "Vanuatu", id: "+678", value: "VU", flag: "🇻🇺" },
  {
    label: "Venezuela, Bolivarian Republic of",
    id: "+58",
    value: "VE",
    flag: "🇻🇪",
  },
  { label: "Viet Nam", id: "+84", value: "VN", flag: "🇻🇳" },
  {
    label: "Virgin Islands, British",
    id: "+1284",
    value: "VG",
    flag: "🇻🇬",
  },
  { label: "Virgin Islands, U.S.", id: "+1340", value: "VI", flag: "🇻🇮" },
  { label: "Wallis and Futuna", id: "+681", value: "WF", flag: "🇼🇫" },
  { label: "Western Sarah", id: "+212", value: "EH", flag: "🇪🇭" },
  { label: "Yemen", id: "+967", value: "YE", flag: "🇾🇪" },
  { label: "Zambia", id: "+260", value: "ZM", flag: "🇿🇲" },
  { label: "Zimbabwe", id: "+263", value: "ZW", flag: "🇿🇼" },
  { label: "Åland Islands", id: "+358", value: "AX", flag: "🇦🇽" },
];
